# Basics of Numpy Arrays

In [21]:
import numpy as np

In [22]:
A = np.array([1, 2, 3, 4])

In [23]:
A[0], A[1], A[-1]

(1, 2, 4)

In [24]:
A[0:], A[:-1]

(array([1, 2, 3, 4]), array([1, 2, 3]))

In [31]:
print(A.shape)    # shape of Array

print(A.dtype)    # Data type of elements

print(A.size)     # Size in bytes of array

(2, 3)
int64
6


# Multidimensional Arrays

In [28]:
A = np.array([
              [1, 2, 3],
              [4, 5, 6]
])

print(A)
print(A.shape)  # shape of matrix
print(A.ndim)   # dimensions of matrix

(2, 3)
2


In [29]:
B = np.array([
              [
               [1, 2, 3],
               [4, 5, 6]
              ],
              [
               [1, 2, 3],
               [4, 5, 6]
              ],
              [
               [1, 2, 3],
               [4, 5, 6]
              ]

])

print(B)
print(B.shape)  # shape of matrix
print(B.ndim)   # dimensions of matrix

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(3, 2, 3)
3


# Linear Algebra

# Generating Arrays

# Statistics