# Basics of Numpy Arrays

In [14]:
import numpy as np

In [15]:
A = np.array([1, 2, 3, 4])

In [16]:
A[0], A[1], A[-1]         # Accessing entries

(1, 2, 4)

In [17]:
A[0:], A[:-1]             # Slicing arrays

(array([1, 2, 3, 4]), array([1, 2, 3]))

In [18]:
print(A.shape)    # shape of Array

print(A.dtype)    # Data type of elements

print(A.size)     # Size in bytes of array

(4,)
int64
4


# Multidimensional Arrays

In [19]:
A = np.array([
              [1, 2, 3],
              [4, 5, 6]
])

print(A)
print(A.shape)  # shape of matrix
print(A.ndim)   # dimensions of matrix

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [21]:
B = np.array([
              [
               [1, 2, 3],
               [4, 5, 6]
              ],
              [
               [1, 2, 3],
               [4, 5, 6]
              ],
              [
               [1, 2, 3],
               [4, 5, 6]
              ]

])

print(B)
print(B.shape)  # shape of matrix
print(B.ndim)   # dimensions of matrix

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(3, 2, 3)
3


# Arithmatic Operations on Arrays

In [22]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

In [23]:
A + B

array([[ 6,  8],
       [10, 12]])

In [24]:
A * B

array([[ 5, 12],
       [21, 32]])

In [25]:
A - B

array([[-4, -4],
       [-4, -4]])

In [26]:
A / B

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

# Linear Algebra

In [27]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
A.shape

(3, 3)

In [28]:
A.T      # Transpose of A

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [29]:
B = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
B.shape

(3, 2)

In [30]:
A.dot(B)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

# Generating Arrays

In [31]:
np.zeros(5)       # array of length 5 and entries equal to zero

array([0., 0., 0., 0., 0.])

In [32]:
np.zeros((3, 3))  # matrix of element zero's

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.ones(5)        # array of length 5 and entries equal to one

array([1., 1., 1., 1., 1.])

In [34]:
np.ones((3, 3))   # matrix of element one's

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.identity(5)    # matrix with main diagonal entries equal to one

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.random.random(size=2)        # array with random entries

array([0.48822172, 0.48003781])

In [38]:
np.random.rand(2, 4)            # matrix with random entries

array([[0.42955753, 0.07943274, 0.69310207, 0.39025647],
       [0.98661654, 0.30275934, 0.89653088, 0.25661675]])

In [39]:
np.arange(2)                    # Array from 0 to (range - 1)

array([0, 1])

In [40]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Statistics

In [43]:
A = np.array([1, 2, 3, 4])

In [44]:
A.sum()       # Sum of all the elements

10

In [45]:
A.mean()      # Mean of all the elements

2.5

In [46]:
A.std()       # Standard deviation of all the elements

1.118033988749895

In [47]:
A.var()       # Variance of all the elements

1.25

In [48]:
A = np.array([[1, 2],
              [3, 4]])

In [49]:
A.sum(axis=0)         # if axis=0 then sum vertically, if axis=1 then sum horizontally

array([4, 6])

In [50]:
A.mean(axis=1)

array([1.5, 3.5])

In [51]:
A.std(axis=0)

array([1., 1.])

In [52]:
A.var(axis=1)

array([0.25, 0.25])