# Basics of Numpy Arrays

In [1]:
import numpy as np

In [ ]:
A = np.array([1, 2, 3, 4])

In [ ]:
A[0], A[1], A[-1]

(1, 2, 4)

In [ ]:
A[0:], A[:-1]

(array([1, 2, 3, 4]), array([1, 2, 3]))

In [ ]:
print(A.shape)    # shape of Array

print(A.dtype)    # Data type of elements

print(A.size)     # Size in bytes of array

(2, 3)
int64
6


# Multidimensional Arrays

In [ ]:
A = np.array([
              [1, 2, 3],
              [4, 5, 6]
])

print(A)
print(A.shape)  # shape of matrix
print(A.ndim)   # dimensions of matrix

(2, 3)
2


In [ ]:
B = np.array([
              [
               [1, 2, 3],
               [4, 5, 6]
              ],
              [
               [1, 2, 3],
               [4, 5, 6]
              ],
              [
               [1, 2, 3],
               [4, 5, 6]
              ]

])

print(B)
print(B.shape)  # shape of matrix
print(B.ndim)   # dimensions of matrix

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(3, 2, 3)
3


# Arithmatic Operations on Arrays

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

In [ ]:
A + B

array([[ 6,  8],
       [10, 12]])

In [ ]:
A * B

array([[ 5, 12],
       [21, 32]])

In [ ]:
A - B

array([[-4, -4],
       [-4, -4]])

In [ ]:
A / B

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

# Linear Algebra

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
A.shape

(3, 3)

In [ ]:
A.T      # Transpose of A

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
B = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
B.shape

(3, 2)

In [ ]:
A.dot(B)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

# Generating Arrays

In [33]:
np.zeros(5)       # array of length 5 and entries equal to zero

array([0., 0., 0., 0., 0.])

In [34]:
np.zeros((3, 3))  # matrix of element zero's

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.ones(5)        # array of length 5 and entries equal to one

array([1., 1., 1., 1., 1.])

In [36]:
np.ones((3, 3))   # matrix of element one's

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.identity(5)    # matrix with main diagonal entries equal to one

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.random.random(size=2)        # array with random entries

array([0.13277805, 0.20246715])

In [40]:
np.random.rand(2, 4)            # matrix with random entries

array([[0.43789193, 0.20258654, 0.72129349, 0.60780937],
       [0.89251273, 0.1477022 , 0.7802932 , 0.11704243]])

In [41]:
np.arange(2)

array([0, 1])

In [42]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Statistics