# Basics of Numpy Arrays

In [1]:
import numpy as np

In [ ]:
A = np.array([1, 2, 3, 4])

In [ ]:
A[0], A[1], A[-1]

(1, 2, 4)

In [ ]:
A[0:], A[:-1]

(array([1, 2, 3, 4]), array([1, 2, 3]))

In [ ]:
print(A.shape)    # shape of Array

print(A.dtype)    # Data type of elements

print(A.size)     # Size in bytes of array

(2, 3)
int64
6


# Multidimensional Arrays

In [ ]:
A = np.array([
              [1, 2, 3],
              [4, 5, 6]
])

print(A)
print(A.shape)  # shape of matrix
print(A.ndim)   # dimensions of matrix

(2, 3)
2


In [ ]:
B = np.array([
              [
               [1, 2, 3],
               [4, 5, 6]
              ],
              [
               [1, 2, 3],
               [4, 5, 6]
              ],
              [
               [1, 2, 3],
               [4, 5, 6]
              ]

])

print(B)
print(B.shape)  # shape of matrix
print(B.ndim)   # dimensions of matrix

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(3, 2, 3)
3


# Arithmatic Operations on Arrays

In [21]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

In [23]:
A + B

array([[ 6,  8],
       [10, 12]])

In [24]:
A * B

array([[ 5, 12],
       [21, 32]])

In [25]:
A - B

array([[-4, -4],
       [-4, -4]])

In [26]:
A / B

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

# Linear Algebra

In [6]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
A.shape

(3, 3)

In [3]:
A.T      # Transpose of A

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [7]:
B = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
B.shape

(3, 2)

In [10]:
A.dot(B)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

# Generating Arrays

# Statistics